[package]
name = "rusty-id"
version = "0.7.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
bevy_reflect = { version = "0.17", optional = true }

[features]
default = []
serde = ["dep:serde"]
bevy_reflect = ["dep:bevy_reflect"]
